name: Update manifest.json depending on the file structure

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    branches:
      - main

jobs:
  updatemanifest:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run updatemanifest.py
        run: python updatemanifest.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update manifest.json
          file_pattern: manifest.json last_modified.txt
          push_options: --force
